
DROP TABLE IF EXISTS measurement;
DROP TABLE IF EXISTS sensor;

CREATE TABLE sensor(
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR (100) NOT NULL,
                       registered_at TIMESTAMP,
                       updated_at TIMESTAMP
);

CREATE TABLE measurement(
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            sensor_id INT REFERENCES sensor(id),
                            value DECIMAL(4,1),
                            raining BOOLEAN,
                            made_at TIMESTAMP
);